server:
  port: 8081
  servlet:
    context-path: /reference-manager

spring:
  application:
    name: reference-manager-service

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3307/reference_manager_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5

app:
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm}
    expiration: 86400000

  kafka:
    topics:
      reference-events: reference.events

  redis:
    ttl:
      airlines: 3600
      stations: 7200
      aircraft: 3600

# Swagger Configuration
# Swagger Configuration - mevcut springdoc k?sm?n? bununla de?i?tir
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    # Context path'i dahil et
    config-url: /reference-manager/v3/api-docs/swagger-config
    oauth2-redirect-url: /reference-manager/swagger-ui/oauth2-redirect.html
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.flightmanagement.reference: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  logging:
    level:
      com.flightmanagement.reference: INFO
      root: WARN